const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
const PUT_SEARCH_RESULTS = 'PUT_SEARCH_RESULTS';
const VIEW_STOCK_DATA = 'VIEW_STOCK_DATA';
const VIEW_STOCK_DATA_SCREEN = 'VIEW_STOCK_DATA_SCREEN';

const SELECT_NEW_RANGE = 'SELECT_NEW_RANGE';

const FETCH_STOCK_DATA = 'FETCH_STOCK_DATA';
const FETCH_STOCK_DATA_SUCCESS = 'FETCH_STOCK_DATA_SUCCESS';
const FETCH_STOCK_DATA_ERROR = 'FETCH_STOCK_DATA_ERROR';

export default {
  FETCH_STOCK_DATA,
  FETCH_STOCK_DATA_ERROR,
  FETCH_STOCK_DATA_SUCCESS,
  CHANGE_SEARCH_QUERY,
  PUT_SEARCH_RESULTS,
  VIEW_STOCK_DATA,
  VIEW_STOCK_DATA_SCREEN,
  SELECT_NEW_RANGE,
};
