const FETCH_STOCK_DATA = 'FETCH_STOCK_DATA';
const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
const PUT_SEARCH_RESULTS = 'PUT_SEARCH_RESULTS';
const VIEW_STOCK_DATA = 'VIEW_STOCK_DATA';
const VIEW_STOCK_DATA_SCREEN = 'VIEW_STOCK_DATA_SCREEN';

export default {
  FETCH_STOCK_DATA,
  CHANGE_SEARCH_QUERY,
  PUT_SEARCH_RESULTS,
  VIEW_STOCK_DATA,
  VIEW_STOCK_DATA_SCREEN,
};
